USE broomy_db;

CALL prnInsCountry('NIGERIA');
CALL prnInsCountry('CANADA'); 
CALL prnInsCountry('UNITED KINGDOM');
CALL prnInsCountry('U.S.A');
CALL prnInsCountry('FRANCE');
CALL prnInsCountry('GERMANY');
CALL prnInsCountry('JAPAN');
CALL prnInsCountry('AFGHANISTAN');
CALL prnInsCountry('ALBANIA');
CALL prnInsCountry('ALGERIA');
CALL prnInsCountry('AMERICAN SAMOA');
CALL prnInsCountry('ANDORRA');
CALL prnInsCountry('AN LA');
CALL prnInsCountry('ANGUILLA');  
CALL prnInsCountry('ANTIGUA AND BARBUDA');
CALL prnInsCountry('ARGENTINA');
CALL prnInsCountry('ARMENIA');
CALL prnInsCountry('ARUBA');
CALL prnInsCountry('AUSTRALIA');
CALL prnInsCountry('AUSTRIA');
CALL prnInsCountry('AZERBAIJAN');  
CALL prnInsCountry('BAHAMAS');
CALL prnInsCountry('BAHRAIN');
CALL prnInsCountry('BANGLADESH');  
CALL prnInsCountry('BARBADOS');
CALL prnInsCountry('BELARUS');
CALL prnInsCountry('BELGIUM');
CALL prnInsCountry('BELIZE');
CALL prnInsCountry('BENIN');
CALL prnInsCountry('BERMUDA'); 
CALL prnInsCountry('BHUTAN');
CALL prnInsCountry('BOLIVIA');
CALL prnInsCountry('BOSNIA & H');
CALL prnInsCountry('BOTSWANA');
CALL prnInsCountry('BRAZIL');
CALL prnInsCountry('BRUNEI DARUSSALAM');
CALL prnInsCountry('BULGARIA');
CALL prnInsCountry('BURKINA FASO');
CALL prnInsCountry('BURUNDI');
CALL prnInsCountry('CAMBODIA');
CALL prnInsCountry('CAMEROON');
CALL prnInsCountry('CAPE VERDE'); 
CALL prnInsCountry('CAYMAN ISLANDS');
CALL prnInsCountry('CENTRAL AFRICAN');
CALL prnInsCountry('REPUBLIC');
CALL prnInsCountry('CHAD');
CALL prnInsCountry('CHILE');
CALL prnInsCountry('CHINA');
CALL prnInsCountry('CHRISTMAS ISLAND');
CALL prnInsCountry('COCOS (KEELING)');
CALL prnInsCountry('ISLANDS');
CALL prnInsCountry('COLOMBIA');
CALL prnInsCountry('COMOROS');
CALL prnInsCountry('CON(');
CALL prnInsCountry('COOK ISLANDS');
CALL prnInsCountry('COSTA RICA');
CALL prnInsCountry('COTE D IVOIRE');  
CALL prnInsCountry('CROATIA (HRVATSKA)');
CALL prnInsCountry('CYPRUS');
CALL prnInsCountry('CZECH REPUBLIC');
CALL prnInsCountry('DENMARK');
CALL prnInsCountry('DJIBOUTI');
CALL prnInsCountry('DOMINICA');
CALL prnInsCountry('DOMINICAN REPUBLIC');
CALL prnInsCountry('ECUADOR');
CALL prnInsCountry('EGYPT');
CALL prnInsCountry('EL SALVADOR');
CALL prnInsCountry('EQUATORIAL GUINEA');
CALL prnInsCountry('ERITREA');
CALL prnInsCountry('ESTONIA');
CALL prnInsCountry('ETHIOPIA');
CALL prnInsCountry('FALKLAND ISLANDS');
CALL prnInsCountry('FAROE ISLANDS');
CALL prnInsCountry('FIJI');
CALL prnInsCountry('FINLAND');  
CALL prnInsCountry('FRENCH GUIANA');
CALL prnInsCountry('FRENCH POLYNESIA');  
CALL prnInsCountry('GABON');
CALL prnInsCountry('GAMBIA GEORGIA');
CALL prnInsCountry('GHANA');
CALL prnInsCountry('GIBRALTAR');
CALL prnInsCountry('GREECE');
CALL prnInsCountry('GREENLAND');  
CALL prnInsCountry('GRENADA');
CALL prnInsCountry('GUADELOUPE');  
CALL prnInsCountry('GUAM');
CALL prnInsCountry('GUATEMALA');
CALL prnInsCountry('GUINEA');
CALL prnInsCountry('GUINEA-BISSAU');
CALL prnInsCountry('GUYANA');
CALL prnInsCountry('HAITI');
CALL prnInsCountry('HOLY SEE ');
CALL prnInsCountry('HONDURAS');
CALL prnInsCountry('HONG KONG');  
CALL prnInsCountry('HUNGARY');  
CALL prnInsCountry('ICELAND');  
CALL prnInsCountry('INDIA');  
CALL prnInsCountry('INDONESIA');  
CALL prnInsCountry('IRELAND');  
CALL prnInsCountry('ISRAEL');  
CALL prnInsCountry('ITALY');  
CALL prnInsCountry('JAMAICA');  
CALL prnInsCountry('JORDAN');  
CALL prnInsCountry('KAZAKHSTAN');  
CALL prnInsCountry('KENYA');  
CALL prnInsCountry('KIRIBATI');  
CALL prnInsCountry('SOUTH KOREA');  
CALL prnInsCountry('KUWAIT');  
CALL prnInsCountry('KYRGYZSTAN');  
CALL prnInsCountry('LAOS');  
CALL prnInsCountry('LATVIA');  
CALL prnInsCountry('LEBANON');  
CALL prnInsCountry('LESOTHO');  
CALL prnInsCountry('LIBERIA');  
CALL prnInsCountry('LIECHTENSTEIN');  
CALL prnInsCountry('LITHUANIA');  
CALL prnInsCountry('LUXEMBOURG');  
CALL prnInsCountry('MACAU');  
CALL prnInsCountry('MACEDONIA');  
CALL prnInsCountry('MADAGASCAR');  
CALL prnInsCountry('MALAWI');  
CALL prnInsCountry('MALAYSIA');  
CALL prnInsCountry('MALDIVES');  
CALL prnInsCountry('MALI');  
CALL prnInsCountry('MALTA');  
CALL prnInsCountry('MARSHALL');  
CALL prnInsCountry('MARTINIQUE');  
CALL prnInsCountry('MAURITANIA');  
CALL prnInsCountry('MAURITIUS');  
CALL prnInsCountry('MAYOTTE');  
CALL prnInsCountry('MEXICO');  
CALL prnInsCountry('MICRONESIA');  
CALL prnInsCountry('MOLDOVA');  
CALL prnInsCountry('MONACO');  
CALL prnInsCountry('MON LIA');  
CALL prnInsCountry('MONTSERRAT');  
CALL prnInsCountry('MOROCCO');  
CALL prnInsCountry('MOZAMBIQUE');  
CALL prnInsCountry('MYANMAR');  
CALL prnInsCountry('NAMIBIA');  
CALL prnInsCountry('NAURU');  
CALL prnInsCountry('NEPAL');  
CALL prnInsCountry('THE NETHERLANDS');  
CALL prnInsCountry('NETHERLANDS ANTILLES');  
CALL prnInsCountry('NEW CALEDONIA');  
CALL prnInsCountry('NEW ZEALAND');  
CALL prnInsCountry('NICARAGUA');  
CALL prnInsCountry('NIGER');  
CALL prnInsCountry('NIUE');  
CALL prnInsCountry('NORFOLK');  
CALL prnInsCountry('ISLAND');  
CALL prnInsCountry('NORTHERN MARIANA');  
CALL prnInsCountry('NORWAY');  
CALL prnInsCountry('OMAN');  
CALL prnInsCountry('PAKISTAN');  
CALL prnInsCountry('PALAU');  
CALL prnInsCountry('PANAMA');  
CALL prnInsCountry('PAPUA NEW GUINEA');  
CALL prnInsCountry('PARAGUAY');  
CALL prnInsCountry('PERU');  
CALL prnInsCountry('PHILIPPINES');  
CALL prnInsCountry('POLAND');  
CALL prnInsCountry('PORTUGAL');  
CALL prnInsCountry('PUERTO RICO');  
CALL prnInsCountry('QATAR');  
CALL prnInsCountry('REUNION');  
CALL prnInsCountry('ROMANIA');  
CALL prnInsCountry('RUSSIA');  
CALL prnInsCountry('RWANDA');  
CALL prnInsCountry('SAINT KITTS & NEVIS');  
CALL prnInsCountry('SAINT LUCIA');  
CALL prnInsCountry('SAINT VINCENT & GRENADINES');  
CALL prnInsCountry('SAMOA');  
CALL prnInsCountry('SAN MARINO');  
CALL prnInsCountry('SAO TOME & P');  
CALL prnInsCountry('SAUDI ARABIA');  
CALL prnInsCountry('SENEGAL');  
CALL prnInsCountry('SEYCHELLES');  
CALL prnInsCountry('SIERRA LEONE');  
CALL prnInsCountry('SINGAPORE');  
CALL prnInsCountry('SLOVAKIA');  
CALL prnInsCountry('SLOVENIA');  
CALL prnInsCountry('SOLOMON');   
CALL prnInsCountry('SOMALIA');  
CALL prnInsCountry('SOUTH AFRICA');  
CALL prnInsCountry('SPAIN');  
CALL prnInsCountry('SRI LANKA');  
CALL prnInsCountry('ST. HELENA');  
CALL prnInsCountry('ST. PIERRE & M');  
CALL prnInsCountry('SURINAME');  
CALL prnInsCountry('SVALBARD & J ISLANDS');  
CALL prnInsCountry('SWAZILAND');  
CALL prnInsCountry('SWEDEN');  
CALL prnInsCountry('SWITZERLAND');  
CALL prnInsCountry('TAIWAN');  
CALL prnInsCountry('TAJIKISTAN');  
CALL prnInsCountry('TANZANIA');  
CALL prnInsCountry('THAILAND');  
CALL prnInsCountry('TOGO');  
CALL prnInsCountry('TONGA');  
CALL prnInsCountry('TRINIDAD AND TOBAGO');  
CALL prnInsCountry('TUNISIA');
CALL prnInsCountry('TURKEY');  
CALL prnInsCountry('TURKMENISTAN');  
CALL prnInsCountry('TURKS & C ISLANDS');  
CALL prnInsCountry('TUVALU');  
CALL prnInsCountry('UGANDA');  
CALL prnInsCountry('UKRAINE');  
CALL prnInsCountry('UNITED ARAB EMIRATES');  
CALL prnInsCountry('URUGUAY');  
CALL prnInsCountry('UZBEKISTAN');  
CALL prnInsCountry('VANUATU');  
CALL prnInsCountry('VENEZUELA');  
CALL prnInsCountry('VIET NAM');  
CALL prnInsCountry('VIRGIN ISLANDS(BRI)');  
CALL prnInsCountry('VIRGIN ISLANDS(U.S.)');  
CALL prnInsCountry('WALLIS & F ISLANDS');  
CALL prnInsCountry('WESTERN SAHARA');  
CALL prnInsCountry('YEMEN');  
CALL prnInsCountry('YU SLAVIA');  
CALL prnInsCountry('ZAIRE');  
CALL prnInsCountry('ZAMBIA');  
CALL prnInsCountry('ZIMBABWE');